### ISSUE TITLE
Expose the possibility to change the log level through the API

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/context-adapter#71]
Implement an API operation to change the log level dynamically.

API to implement:

```
POST /admin/log?level=info
```

The value of the `level` parameter is interpreted in case insensitive way and the valid values are: `FATAL`, `ERROR`, `WARNING`, `INFO`, `DEBUG`

Result in the happy case: `200 OK` (without payload)

Result in the case of error: `400 Bad Request`

``` javascript
{
   "error": "not supported log level"
}
```

**Comment by fgalan** [comment]
At the end, after discussion, PUT is going to be used as verb.

**Comment by fgalan** [comment]
In addition, error:

```
{
   "error": "not supported log level"
}
```

has changed to:

```
{
   "error": "invalid log level"
}
```

(See complete specification in source JIRA item)
